[package]
name = "image_denoising"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"
image = "0.24.7"
rfd = "0.12.1"
rayon = "1.8.0"
zerofrom = "0.1.6"
zerofrom-derive = "0.1.6"
winapi = { version = "0.3.9", features = ["winuser", "windef"] }